# Generated by Django 5.0.6 on 2024-07-07 06:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='fecha_lanzamiento',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='libro',
            name='portada',
            field=models.ImageField(blank=True, null=True, upload_to='portadas/'),
        ),
        migrations.AddField(
            model_name='libro',
            name='sinopsis',
            field=models.CharField(default='No se ha creado una sinopsis para este libro', max_length=500),
        ),
    ]
