# Generated by Django 5.0.6 on 2024-07-07 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_libro_fecha_lanzamiento_libro_portada_libro_sinopsis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='sinopsis',
            field=models.CharField(default='No se ha creado una sinopsis para este libro', max_length=2000),
        ),
    ]
